import jsPDF from 'jspdf';
import { Course } from '../types/Course';
import { letterToPoints, calculateGPA } from './gradeUtils';

interface PDFExportOptions {
  courses: Course[];
  currentGPA: number;
  studentName?: string;
}

// Get grade assessment text
const getGPAAssessment = (gpa: number): string => {
  if (gpa < 1) return 'Very Poor';
  if (gpa < 2) return 'Poor';
  if (gpa < 2.5) return 'Acceptable';
  if (gpa < 3) return 'Good';
  if (gpa < 3.5) return 'Very Good';
  return 'Excellent';
};

// Calculate course impact
const calculateCourseImpact = (courses: Course[], courseIndex: number): number => {
  const coursesWithGrades = courses.filter(c => c.grade !== null);
  const coursesBefore = coursesWithGrades.slice(0, courseIndex);
  const coursesIncluding = coursesWithGrades.slice(0, courseIndex + 1);
  
  const gpaBefore = coursesBefore.length > 0 ? calculateGPA(coursesBefore) : 0;
  const gpaIncluding = calculateGPA(coursesIncluding);
  
  return gpaIncluding - gpaBefore;
};

export const generateGradeReport = ({ courses, currentGPA, studentName }: PDFExportOptions): void => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - (2 * margin);
  
  let yPos = margin;
  
  // Add watermark function
  const addWatermark = () => {
    doc.saveGraphicsState();
    // @ts-ignore - GState is valid but TypeScript doesn't recognize it
    doc.setGState(new doc.GState({ opacity: 0.1 }));
    doc.setFontSize(60);
    doc.setTextColor(255, 121, 85);
    
    // Rotate and center the watermark
    doc.text('UNOFFICIAL', pageWidth / 2, pageHeight / 2, {
      angle: 45,
      align: 'center',
    });
    
    doc.restoreGraphicsState();
  };
  
  // Add header
  const addHeader = () => {
    // Logo/Title area
    doc.setFillColor(255, 121, 85);
    doc.rect(margin, yPos, contentWidth, 15, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('GPA GRADE REPORT', pageWidth / 2, yPos + 10, { align: 'center' });
    
    yPos += 20;
    
    // Institution info
    doc.setTextColor(80, 80, 80);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Faculty of Computer and Artificial Intelligence', pageWidth / 2, yPos, { align: 'center' });
    yPos += 6;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text('Cairo University', pageWidth / 2, yPos, { align: 'center' });
    yPos += 10;
    
    // Date and document info
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    const currentDate = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });
    doc.text(`Generated: ${currentDate}`, margin, yPos);
    yPos += 15;
  };
  
  // Add disclaimer banner
  const addDisclaimerBanner = () => {
    doc.setFillColor(255, 243, 224);
    doc.setDrawColor(251, 191, 36);
    doc.setLineWidth(0.5);
    doc.rect(margin, yPos, contentWidth, 25, 'FD');
    
    doc.setFontSize(10);
    doc.setTextColor(120, 53, 15);
    doc.setFont('helvetica', 'bold');
    doc.text('? IMPORTANT NOTICE', margin + 5, yPos + 7);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    const disclaimerLines = doc.splitTextToSize(
      'This is an UNOFFICIAL grade report generated by a student tool. Results may be inaccurate and subject to change. This document is NOT valid for official purposes. Always verify grades through official university channels.',
      contentWidth - 10
    );
    doc.text(disclaimerLines, margin + 5, yPos + 13);
    
    yPos += 30;
  };
  
  // Add student info section
  const addStudentInfo = () => {
    doc.setFillColor(248, 250, 252);
    doc.rect(margin, yPos, contentWidth, 20, 'F');
    
    doc.setFontSize(11);
    doc.setTextColor(30, 41, 59);
    doc.setFont('helvetica', 'bold');
    
    if (studentName) {
      doc.text(`Student: ${studentName}`, margin + 5, yPos + 8);
    }
    
    const assessment = getGPAAssessment(currentGPA);
    doc.text(`GPA: ${currentGPA.toFixed(2)} / 4.00`, margin + 5, yPos + 15);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(`Assessment: ${assessment}`, pageWidth - margin - 5, yPos + 15, { align: 'right' });
    
    yPos += 25;
  };
  
  // Add summary statistics
  const addSummaryStats = () => {
    const coursesWithGrades = courses.filter(c => c.grade !== null);
    const totalCredits = coursesWithGrades.reduce((sum, c) => sum + c.hours, 0);
    const passedCourses = coursesWithGrades.filter(c => c.grade !== 'F').length;
    const failedCourses = coursesWithGrades.filter(c => c.grade === 'F').length;
    
    doc.setFontSize(11);
    doc.setTextColor(30, 41, 59);
    doc.setFont('helvetica', 'bold');
    doc.text('Academic Summary', margin, yPos);
    yPos += 8;
    
    // Stats boxes
    const boxWidth = (contentWidth - 10) / 3;
    const boxHeight = 20;
    
    // Total Credits
    doc.setFillColor(229, 231, 235);
    doc.roundedRect(margin, yPos, boxWidth, boxHeight, 3, 3, 'F');
    doc.setFontSize(16);
    doc.setTextColor(59, 130, 246);
    doc.setFont('helvetica', 'bold');
    doc.text(totalCredits.toString(), margin + boxWidth / 2, yPos + 10, { align: 'center' });
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.setFont('helvetica', 'normal');
    doc.text('Total Credits', margin + boxWidth / 2, yPos + 16, { align: 'center' });
    
    // Passed Courses
    doc.setFillColor(229, 231, 235);
    doc.roundedRect(margin + boxWidth + 5, yPos, boxWidth, boxHeight, 3, 3, 'F');
    doc.setFontSize(16);
    doc.setTextColor(34, 197, 94);
    doc.setFont('helvetica', 'bold');
    doc.text(passedCourses.toString(), margin + boxWidth * 1.5 + 5, yPos + 10, { align: 'center' });
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.setFont('helvetica', 'normal');
    doc.text('Passed', margin + boxWidth * 1.5 + 5, yPos + 16, { align: 'center' });
    
    // Failed Courses
    doc.setFillColor(229, 231, 235);
    doc.roundedRect(margin + (boxWidth + 5) * 2, yPos, boxWidth, boxHeight, 3, 3, 'F');
    doc.setFontSize(16);
    doc.setTextColor(239, 68, 68);
    doc.setFont('helvetica', 'bold');
    doc.text(failedCourses.toString(), margin + boxWidth * 2.5 + 10, yPos + 10, { align: 'center' });
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.setFont('helvetica', 'normal');
    doc.text('Failed', margin + boxWidth * 2.5 + 10, yPos + 16, { align: 'center' });
    
    yPos += 28;
  };
  
  // Add course list with impacts
  const addCourseList = () => {
    const coursesWithGrades = courses.filter(c => c.grade !== null);
    
    if (coursesWithGrades.length === 0) {
      return;
    }
    
    doc.setFontSize(11);
    doc.setTextColor(30, 41, 59);
    doc.setFont('helvetica', 'bold');
    doc.text('Course Performance Details', margin, yPos);
    yPos += 8;
    
    // Table header
    doc.setFillColor(255, 121, 85);
    doc.rect(margin, yPos, contentWidth, 8, 'F');
    
    doc.setFontSize(8);
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.text('Course Name', margin + 2, yPos + 5.5);
    doc.text('Grade', margin + contentWidth - 45, yPos + 5.5);
    doc.text('Credits', margin + contentWidth - 30, yPos + 5.5);
    doc.text('Impact', margin + contentWidth - 15, yPos + 5.5);
    
    yPos += 10;
    
    // Table rows
    coursesWithGrades.forEach((course, index) => {
      // Check if we need a new page
      if (yPos > pageHeight - 40) {
        doc.addPage();
        addWatermark();
        yPos = margin;
      }
      
      const impact = calculateCourseImpact(coursesWithGrades, index);
      
      // Alternate row colors
      if (index % 2 === 0) {
        doc.setFillColor(248, 250, 252);
        doc.rect(margin, yPos - 5, contentWidth, 7, 'F');
      }
      
      doc.setFontSize(8);
      doc.setTextColor(30, 41, 59);
      doc.setFont('helvetica', 'normal');
      
      // Course name (truncate if too long)
      const maxNameWidth = contentWidth - 55;
      let courseName = course.name;
      if (doc.getTextWidth(courseName) > maxNameWidth) {
        while (doc.getTextWidth(courseName + '...') > maxNameWidth && courseName.length > 0) {
          courseName = courseName.slice(0, -1);
        }
        courseName += '...';
      }
      doc.text(courseName, margin + 2, yPos);
      
      // Grade
      doc.setFont('helvetica', 'bold');
      const gradeColor = course.grade === 'F' ? [239, 68, 68] : 
                        letterToPoints(course.grade) >= 3.5 ? [34, 197, 94] :
                        letterToPoints(course.grade) >= 3.0 ? [59, 130, 246] : [251, 191, 36];
      doc.setTextColor(gradeColor[0], gradeColor[1], gradeColor[2]);
      doc.text(course.grade || '-', margin + contentWidth - 45, yPos);
      
      // Credits
      doc.setTextColor(100, 116, 139);
      doc.setFont('helvetica', 'normal');
      doc.text(course.hours.toString(), margin + contentWidth - 30, yPos);
      
      // Impact
      const impactColor = impact >= 0 ? [34, 197, 94] : [239, 68, 68];
      doc.setTextColor(impactColor[0], impactColor[1], impactColor[2]);
      doc.setFont('helvetica', 'bold');
      doc.text((impact >= 0 ? '+' : '') + impact.toFixed(3), margin + contentWidth - 15, yPos);
      
      yPos += 7;
    });
    
    yPos += 10;
  };
  
  // Add insights section
  const addInsights = () => {
    const coursesWithGrades = courses.filter(c => c.grade !== null);
    const lowGradeCourses = coursesWithGrades.filter(c => letterToPoints(c.grade) < 3.0 && c.hours >= 2);
    
    if (lowGradeCourses.length === 0) {
      return;
    }
    
    // Check if we need a new page
    if (yPos > pageHeight - 60) {
      doc.addPage();
      addWatermark();
      yPos = margin;
    }
    
    doc.setFontSize(11);
    doc.setTextColor(30, 41, 59);
    doc.setFont('helvetica', 'bold');
    doc.text('Recommendations', margin, yPos);
    yPos += 8;
    
    doc.setFillColor(239, 246, 255);
    doc.setDrawColor(59, 130, 246);
    doc.setLineWidth(0.5);
    doc.roundedRect(margin, yPos, contentWidth, 30, 3, 3, 'FD');
    
    doc.setFontSize(9);
    doc.setTextColor(30, 64, 175);
    doc.setFont('helvetica', 'bold');
    doc.text('?? Courses with Improvement Potential:', margin + 5, yPos + 7);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(51, 65, 85);
    
    let insightY = yPos + 14;
    lowGradeCourses.slice(0, 3).forEach((course, index) => {
      const text = `${index + 1}. ${course.name} (${course.grade}) - ${course.hours} credits`;
      doc.text(text, margin + 5, insightY);
      insightY += 5;
    });
    
    yPos += 35;
  };
  
  // Add footer with disclaimers and link
  const addFooter = () => {
    const footerY = pageHeight - 25;
    
    doc.setDrawColor(203, 213, 225);
    doc.setLineWidth(0.5);
    doc.line(margin, footerY, pageWidth - margin, footerY);
    
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.setFont('helvetica', 'italic');
    doc.text('DISCLAIMER: This is an unofficial document generated by a student tool.', pageWidth / 2, footerY + 5, { align: 'center' });
    doc.text('The website and its maker are not responsible for any misuse of this score report.', pageWidth / 2, footerY + 9, { align: 'center' });
    doc.text('Always verify your grades through official university channels.', pageWidth / 2, footerY + 13, { align: 'center' });
    
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(255, 121, 85);
    doc.textWithLink('Generated by: GPA Calculator Tool', pageWidth / 2, footerY + 18, { 
      align: 'center',
      url: 'https://zzokm.github.io/gpa/'
    });
  };
  
  // Generate the PDF
  addWatermark();
  addHeader();
  addDisclaimerBanner();
  addStudentInfo();
  addSummaryStats();
  addCourseList();
  addInsights();
  addFooter();
  
  // Save the PDF
  const fileName = `GPA_Report_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
};
